#!/usr/bin/env php
<?php

require_once __DIR__ . "/library.php";

if ($argc == 1) {
    echo "Please specify path to the directory\n";
    exit(1);
}


$dir = new RecursiveDirectoryIterator($argv[1]);
$iter = new RecursiveIteratorIterator($dir);

$certs = new RegexIterator(
    $iter,
    '/^.+\.(crt|pem)/i',
    RecursiveRegexIterator::MATCH
);

foreach ($certs as $path) {
    try {
        $expirationDate = "";
        $inform = "";
        $format = "";

        list ($inform, $format) = detectCertFormat($path);
        $cert = parseFormattedCert(readCertificate($path, $inform, $format));

        if (isExpired($cert)) {
            $expirationDate = date('Y-m-d H:i:s e', $cert["expires"]);
            echo "Certificate {$path} expired on {$expirationDate}\n";
        }
    } catch(Exception $e) {
        file_put_contents("php://stderr", "^^ Unable to load certificate {$cert}\n");
    }
}
